### ISSUE TITLE
404 on retina images

### ISSUE THREAD

**Issue by stefro** [onigoetz/imagecache#8]
Hi,
I like this package a lot, just included it in a first project.

I don't like to use retina.js since it tries to find .@2x images from ALL the images on the website. This results in a huge amount of 404 on every page.

I've been using this little piece of JQuery for years now:
```
    // hires images
    if (window.devicePixelRatio == 2) {
        var images = $("img.hires");

        // loop through the images and make them hi-res
        for(var i = 0; i < images.length; i++) {

            // create new image name
            var imageType = images[i].src.substr(-4);
            var imageName = images[i].src.substr(0, images[i].src.length - 4);
            imageName += "@2x" + imageType;

            //rename image
            images[i].src = imageName;
        }
    }
```
It will replace only the images with the class 'hires'. This way I'm in charge of which images can be @2x.
It will never result in a 404 this way.

The stranges thing happens when I use this imagecache package. As soon as browsercaching is ON. I get 404 errors on all the retina images in the console. However, the correct (@2x) images ARE loaded!

I enable browsercache like this (on NGINX):
```
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff|ttf|otf|svg|woff2|eot)$ {
        expires 1y;
        add_header Pragma public;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    }
```
Hope anyone can figure out what is going wrong.

**Comment by onigoetz** [comment]
Hi,
Thanks for using my package, I'm glad you like it.

You're right, this is a strange behaviour.

Just to be sure, I investigate in the right direction, what integration are you using ? (laravel, slim or raw ?)

Also, the first time the images are requested, they're created on disk, is the path correctly generated or is it hitting the image generation everytime ?

With this information I will probably be able to track down the source of the problem

**Comment by stefro** [comment]
Hi, i'm using it in Laravel 5.2.
It happens every time, so not only on the first time when the image is generated first (because that would make sense).
I think the path must be ok, because the image eventually is loaded in the page. I think it might have something to do with the image url (image@2x.jpg) redirected to /cache/whatever@2x/image.jpg

**Comment by onigoetz** [comment]
Okay, so I investigated, and it seems I made a very weird thing when implementing retina images.

Instead of writing an image with the name image@2x.jpg in the folder, so that apache/nginx can just serve the image the next time, i create a folder `preset@2x`. I don't know why I did it that way as it goes against the idea of the package...

In any case, the behaviour is changed to what it should be the url `/cache/whatever/image@2x.jpg` will create a file in `cache/whatever/image@2x.jpg`

You can try it by depending on `dev-master` if it solves your problem, I will release that fix.

**Comment by stefro** [comment]
Perfect!
I only get a 404 when the image needs to be created for the first time, this is expected behavior.
Thanks for fixing this!

**Comment by onigoetz** [comment]
Actually, the first call should not result in a 404.

The first call will generate the image based on the presets and the filename to find the original image in big resolution.

If you open the image in a new tab, you should have a more precise error message, what is it ?

**Comment by stefro** [comment]
Hi, 
There is no error when I do that. The file gets generated and opened. 
For some reason this only happens when browsercache is enabled on nginx.
It only happens ONCE when the image doesn't exist in the cache yet.

This is a timeline of what (I think) happens:
1. The page is loaded with the @1x image -> ok.
2. JQuery replaces the filename, file doesn't exist (yet) -> 404
3. Images gets created
4. image gets loaded (auto retry??)

On every other pageload there will never be a 404 again as long as the image is already generated. This does it for me. I don't care about that first time the image has to be generated.

**Comment by onigoetz** [comment]
Okay, i'll close the issue then as it works, but I will investigate a bit more on why this 404 goes through. Maybe there is an auto-retry, but I dont know where that would come from
